export const queryKeys = {
  schools: {
    all:     ()           => ['schools'] as const,
    active:  ()           => ['schools', 'active'] as const,
    detail:  (id: string) => ['schools', id] as const,
    culture: (id: string) => ['schools', id, 'culture'] as const,
  },
  auth: {
    me: () => ['auth', 'me'] as const,
  },
  dailyContent: {
    today: () => ['daily-content', 'today'] as const,
  },
  notes: {
    all:          (filters?: object) => ['notes', filters] as const,
    school:       (filters?: object) => ['notes', 'school', filters] as const,
    schoolDetail: (id: string)       => ['notes', 'school', id] as const,
    detail:       (id: string)       => ['notes', id] as const,
    status:       (id: string)       => ['notes', id, 'status'] as const,
  },
  conformity: {
    all:       (filters?: object) => ['conformity', filters] as const,
    forNote:   (noteId: string)   => ['conformity', 'note', noteId] as const,
    detail:    (id: string)       => ['conformity', id] as const,
    status:    (id: string)       => ['conformity', id, 'status'] as const,
  },
  adminUsers: {
    all:    (filters?: object) => ['admin', 'users', filters] as const,
    detail: (id: string)       => ['admin', 'users', id] as const,
  },
  adminClasses:    () => ['admin', 'classes'] as const,
  adminSubjects:   () => ['admin', 'subjects'] as const,
  subjects:        (classId?: string | null) => ['subjects', classId ?? 'all'] as const,
  adminSchool:     () => ['admin', 'school'] as const,
  adminCulture:    () => ['admin', 'culture'] as const,
  adminDailyContent: (filters?: object) => ['admin', 'daily-content', filters] as const,
  platformSchools: () => ['platform', 'schools'] as const,
  quiz: {
    all:                (filters?: object) => ['quiz', filters] as const,
    detail:             (id: string)       => ['quiz', id] as const,
    status:             (id: string)       => ['quiz', id, 'status'] as const,
    attempt:            (id: string)       => ['quiz', id, 'attempt'] as const,
    performance:        ()                 => ['quiz', 'performance'] as const,
    performanceHistory: ()                 => ['quiz', 'performance', 'history'] as const,
    classHistory:       ()                 => ['quiz', 'teacher', 'class-history'] as const,
    teacherStudents:    ()                 => ['quiz', 'teacher', 'students'] as const,
    preferences:        ()                 => ['quiz', 'preferences'] as const,
    subjectLimits:      (subject?: string) => ['quiz', 'subject-limits', subject] as const,
    teacherThresholds:  ()                 => ['quiz', 'teacher', 'thresholds'] as const,
    subjectStats:       (subject: string)  => ['quiz', 'subject-stats', subject] as const,
    topicStats:         (subject: string, topic: string) => ['quiz', 'topic-stats', subject, topic] as const,
  },
  lessonDocs: {
    all:       (filters?: object) => ['lesson-docs', filters] as const,
    detail:    (id: string)       => ['lesson-docs', id] as const,
    versions:  (id: string)       => ['lesson-docs', id, 'versions'] as const,
    adminAll:  (filters?: object) => ['admin', 'lesson-docs', filters] as const,
    adminDetail: (id: string)     => ['admin', 'lesson-docs', id] as const,
    distributed: (filters?: object) => ['lesson-docs', 'distributed', filters] as const,
  },
  lessonPlans: {
    all:    (filters?: object) => ['lesson-plans', filters] as const,
    detail: (id: string)       => ['lesson-plans', id] as const,
    admin:  (filters?: object) => ['admin', 'lesson-plans', filters] as const,
  },
};
