export const STANDARD_SUBJECTS = [
  'Mathematics',
  'English Language',
  'Biology',
  'Chemistry',
  'Physics',
  'Geography',
  'History',
  'Economics',
  'Government',
  'Literature in English',
  'Further Mathematics',
  'Agricultural Science',
  'Civic Education',
  'Computer Science',
  'Technical Drawing',
  'Fine Arts',
  'Music',
  'Home Economics',
  'Commerce',
  'Accounting',
  'French',
  'Yoruba',
  'Igbo',
  'Hausa',
  'Islamic Studies',
  'Christian Religious Studies',
  'Physical Education',
  'Social Studies',
  'Basic Science',
  'Basic Technology',
] as const;
